server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: payroll
          uri: lb://PAYROLL
          predicates:
            - Path=/payroll/**
        - id: worker
          uri: lb://WORKER
          predicates:
            - Path=/worker/**


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka